apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment-dev
  labels:
    app: nginx-deployment-dev
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: nginx-deployment-dev
    spec:
      containers:
      - name: nginx-deployment-dev
        image: nginx:1.15.5
        ports:
        - containerPort: 80
